# This is a basic workflow to help you get started with Actions

name: Plan / Test On PR

on:
  pull_request:
    branches:
      - master

jobs:
  job1:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

      - name: Run terraform fmt check
        run: terraform fmt 
     
     
      

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform
        run: |
          cd demo
          terraform init -input=false          

      - name: Plan Terraform
        run: |
          cd demo
          terraform plan -input=false -no-color          
      - name: Apply Terraform
        run: |
          cd demo
          terraform apply 
               
     
